language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
    - LIBRE=re LIBREM=rem

sudo: require

addons:
    apt:
        packages:
        - libavcodec-dev
        - libavdevice-dev
        - libavformat-dev
        - libgtk2.0-dev
        - libjack-jackd2-dev
        - libmpg123-dev
        - libopus-dev
        - libpulse-dev
        - libsndfile1-dev
        - libspandsp-dev
        - libssl-dev
    homebrew:
        packages:
        - codec2
        - fdk-aac
        - ffmpeg
        - jack
        - mpg123
        - spandsp
        update: true

install:
    - git clone https://github.com/creytiv/re.git
    - git clone https://github.com/creytiv/rem.git
    - curl -OL 'https://github.com/alfredh/pytools/raw/master/ccheck.py'
    - for p in ${LIBRE} ${LIBREM}; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script: 
    - make V=1 CCACHE= EXTRA_CFLAGS=-Werror info test modules
    - make clean; make CCACHE= STATIC=yes
    - python2 ccheck.py
