language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
    - LIBRE=re LIBREM=rem

sudo: require

jobs:
  include:
      - name: OpenSSL 1.0.2g
        os: linux
        dist: xenial
        addons:
          apt:
            update: false
        stage: openssl
      - name: OpenSSL 1.1.1f
        os: linux
        dist: focal
        addons:
          apt:
            update: false
        stage: openssl
      - name: macOS 10.15.5
        os: osx
        osx_image: xcode12.0
        stage: openssl
      - name: LibreSSL
        os: linux
        addons:
          apt:
            update: false
        dist: xenial
        script:
          - wget "https://github.com/baresip/ci/releases/download/v0.1/assets.tar.gz"
          - tar -xf assets.tar.gz
          - make EXTRA_CFLAGS="-Iassets/libressl/include -Werror" EXTRA_LFLAGS="-Lassets/libressl" CCACHE=;
        stage: openssl
      - name: OpenSSL 1.1.1g no-deprecated
        os: linux
        dist: xenial
        addons:
          apt:
            update: false
        script:
          - wget "https://github.com/baresip/ci/releases/download/v0.1/assets.tar.gz"
          - tar -xf assets.tar.gz
          - make EXTRA_CFLAGS="-Iassets/openssl/include -Werror" EXTRA_LFLAGS="-Lassets/openssl" CCACHE=;
        stage: openssl

stages:
    - test
    - openssl

addons:
    apt:
        packages:
        - libavcodec-dev
        - libavdevice-dev
        - libavformat-dev
        - libgtk2.0-dev
        - libjack-jackd2-dev
        - libmpg123-dev
        - libopus-dev
        - libpulse-dev
        - libsndfile1-dev
        - libspandsp-dev
        - libssl-dev
    homebrew:
        packages:
        - codec2
        - fdk-aac
        - ffmpeg
        - jack
        - mpg123
        - spandsp
        update: false

install:
    - git clone https://github.com/baresip/re.git
    - git clone https://github.com/creytiv/rem.git
    - for p in ${LIBRE} ${LIBREM}; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script: 
    - make V=1 CCACHE= EXTRA_CFLAGS=-Werror info test modules
    - make clean; make CCACHE= STATIC=yes
    - make ccheck
